--local functions
local function config(name)
    return settings.startup['fu_materials_'..name].value
end

local function sprite(name)
    return '__248k__/ressources/fusion/fu_materials/fu_materials_'..name
end

--item
data:extend({
    {
        name = 'fu_materials_energy_crystal',
        type = 'item',
        icon = sprite('energy_crystal.png'),
        icon_size = 64,
        stack_size = 100,
        subgroup = 'fu_item_subgroup_a',
        order = 'a-a',
    },
    {
        name = 'fu_materials_energy_charged_crystal',
        type = 'item',
        icon = sprite('energy_crystal_charged.png'),
        icon_size = 64,
        stack_size = 100,
        subgroup = 'fu_item_subgroup_a',
        order = 'a-a',
        fuel_glow_color = {r=0.1,g=0.74,b=0.39,a=0.5},
        fuel_category = 'charged_fuel',
        fuel_acceleration_multiplier = 1,
        fuel_emissions_multiplier = 1,
        fuel_top_speed_multiplier = 1,
        fuel_value = '300MJ',
        burnt_result = 'fu_materials_energy_crystal',
    },
    {
        name = 'fu_materials_refined_crystal',
        type = 'item',
        icon = sprite('refined_crystal.png'),
        icon_size = 64,
        stack_size = 100,
        subgroup = 'fu_item_subgroup_a',
        order = 'a-a',
    },
    {
        name = 'fu_materials_pure_lead',
        type = 'item',
        icon = sprite('pure_lead.png'),
        icon_size = 64,
        stack_size = 100,
        subgroup = 'fu_item_subgroup_a',
        order = 'a-a',
    },
    {
        name = 'fu_materials_KFK',
        type = 'item',
        icon = sprite('KFK.png'),
        icon_size = 64,
        stack_size = 100,
        subgroup = 'fu_item_subgroup_b',
        order = 'a-a',
    },
    {
        name = 'fu_materials_TIM',
        type = 'item',
        icon = sprite('TIM.png'),
        icon_size = 64,
        stack_size = 100,
        subgroup = 'fu_item_subgroup_b',
        order = 'a-a',
    },
    {
        name = 'fu_materials_magnet',
        type = 'item',
        icon = sprite('magnet.png'),
        icon_size = 64,
        stack_size = 100,
        subgroup = 'fu_item_subgroup_b',
        order = 'a-a',
    },
    {
        name = 'fu_materials_carbon_fiber',
        type = 'item',
        icon = sprite('carbon_fiber.png'),
        icon_size = 64,
        stack_size = 100,
        subgroup = 'fu_item_subgroup_b',
        order = 'a-a',
    },
    {
        name = 'fu_materials_plasma_card',
        type = 'item',
        icon = sprite('plasma_card.png'),
        icon_size = 64,
        stack_size = 100,
        subgroup = 'fu_item_subgroup_c',
        order = 'c-a',
    },
    {
        name = 'fu_materials_laser_card',
        type = 'item',
        icon = sprite('laser_card.png'),
        icon_size = 64,
        stack_size = 100,
        subgroup = 'fu_item_subgroup_c',
        order = 'c-a',
    },
    {
        name = 'fu_materials_magnet_card',
        type = 'item',
        icon = sprite('magnet_card.png'),
        icon_size = 64,
        stack_size = 100,
        subgroup = 'fu_item_subgroup_c',
        order = 'c-a',
    },
    {
        name = 'fu_materials_fusion_card',
        type = 'item',
        icon = sprite('fusion_card.png'),
        icon_size = 64,
        stack_size = 100,
        subgroup = 'fu_item_subgroup_c',
        order = 'c-a',
    },
    {
        name = 'fu_materials_empty_container',
        type = 'item',
        icon = sprite('empty_container.png'),
        icon_size = 64,
        stack_size = 1,
        subgroup = 'fu_item_subgroup_b',
        order = 'f-a',
    },
    {
        name = 'fu_materials_charged_container',
        type = 'item',
        icon = sprite('charged_container.png'),
        icon_size = 64,
        stack_size = 1,
        subgroup = 'fu_item_subgroup_b',
        order = 'f-a',
    },
    {
        name = 'fu_materials_stone',
        type = 'item',
        icon = sprite('stone.png'),
        icon_size = 64,
        stack_size = 100,
        subgroup = 'fi_item_subgroup_a',
        order = 'f-a',
    },
})
