--local functions
local function config(name)
    return settings.startup[name].value
end

local function sprite(name)
    return '__248k__/ressources/elements/'..name
end

data:extend({
    {
        name = 'fu_hydrogen',
        type = 'fluid',
        icon = sprite('fu_hydrogen.png'),
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        heat_capacity = '1kJ',
        base_color = { r=0.0, g=0.3, b=0.4 }, 
		flow_color = { r=0.0, g=0.3, b=0.4 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0.290,
        subgroup = 'fu_item_subgroup_e',
        order = 'a-a',
    },
    {
        name = 'fu_oxygen',
        type = 'fluid',
        icon = sprite('fu_oxygen.png'),
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        heat_capacity = '10kJ',
        base_color = { r=0.0, g=0.3, b=0.4 }, 
		flow_color = { r=0.0, g=0.3, b=0.4 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0.290,
        subgroup = 'fu_item_subgroup_e',
        order = 'a-b',
    },
    {
        name = 'fu_protium',
        type = 'fluid',
        icon = sprite('fu_protium.png'),
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        heat_capacity = '1kJ',
        base_color = { r=0.0, g=0.3, b=0.4 }, 
		flow_color = { r=0.0, g=0.3, b=0.4 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0.290,
        subgroup = 'fu_item_subgroup_f',
        order = 'a-a',
    },
    {
        name = 'fu_deuterium',
        type = 'fluid',
        icon = sprite('fu_deuterium.png'),
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        heat_capacity = '1kJ',
        base_color = { r=0.0, g=0.3, b=0.4 }, 
		flow_color = { r=0.0, g=0.3, b=0.4 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0.290,
        subgroup = 'fu_item_subgroup_f',
        order = 'a-a',
    },
    {
        name = 'fu_tritium',
        type = 'fluid',
        icon = sprite('fu_tritium.png'),
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        heat_capacity = '1kJ',
        base_color = { r=0.0, g=0.3, b=0.4 }, 
		flow_color = { r=0.0, g=0.3, b=0.4 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0.290,
        subgroup = 'fu_item_subgroup_f',
        order = 'a-a',
    },
    {
        name = 'fu_lithium_6',
        type = 'fluid',
        icon = sprite('fu_lithium_6.png'),
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        heat_capacity = '1kJ',
        base_color = { r=0.0, g=0.3, b=0.4 }, 
		flow_color = { r=0.0, g=0.3, b=0.4 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0.290,
        subgroup = 'fu_item_subgroup_f',
        order = 'a-a',
    },
    {
        name = 'fu_helium_3',
        type = 'fluid',
        icon = sprite('fu_helium_3.png'),
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        heat_capacity = '1kJ',
        base_color = { r=0.0, g=0.3, b=0.4 }, 
		flow_color = { r=0.0, g=0.3, b=0.4 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0.290,
        subgroup = 'fu_item_subgroup_f',
        order = 'a-a',
    },
    {
        name = 'fu_helium_4',
        type = 'fluid',
        icon = sprite('fu_helium_4.png'),
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        heat_capacity = '1kJ',
        base_color = { r=0.0, g=0.3, b=0.4 }, 
		flow_color = { r=0.0, g=0.3, b=0.4 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0.290,
        subgroup = 'fu_item_subgroup_f',
        order = 'a-a',
    },
    --heated plasma
    {
        name = 'fu_protium_heated',
        type = 'fluid',
        icon = sprite('fu_protium_heated.png'),
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        heat_capacity = '1kJ',
        base_color = { r=0.0, g=0.3, b=0.4 }, 
		flow_color = { r=0.0, g=0.3, b=0.4 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0.290,
        subgroup = 'fu_item_subgroup_f',
        order = 'a-a',
    },
    {
        name = 'fu_iron_heated',
        type = 'fluid',
        icon = sprite('fu_iron_heated.png'),
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        heat_capacity = '1kJ',
        base_color = { r=0.0, g=0.3, b=0.4 }, 
		flow_color = { r=0.0, g=0.3, b=0.4 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0.290,
        subgroup = 'fu_item_subgroup_f',
        order = 'a-a',
    },
    {
        name = 'fu_iron',
        type = 'fluid',
        icon = sprite('fu_iron.png'),
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        heat_capacity = '1kJ',
        base_color = { r=0.0, g=0.3, b=0.4 }, 
		flow_color = { r=0.0, g=0.3, b=0.4 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0.290,
        subgroup = 'fu_item_subgroup_f',
        order = 'a-a',
    },
    {
        name = 'fu_copper',
        type = 'fluid',
        icon = sprite('fu_copper.png'),
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        heat_capacity = '1kJ',
        base_color = { r=0.0, g=0.3, b=0.4 }, 
		flow_color = { r=0.0, g=0.3, b=0.4 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0.290,
        subgroup = 'fu_item_subgroup_f',
        order = 'a-a',
    },
    {
        name = 'fu_copper_heated',
        type = 'fluid',
        icon = sprite('fu_copper_heated.png'),
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        heat_capacity = '1kJ',
        base_color = { r=0.0, g=0.3, b=0.4 }, 
		flow_color = { r=0.0, g=0.3, b=0.4 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0.290,
        subgroup = 'fu_item_subgroup_f',
        order = 'a-a',
    },
    {
        name = 'fu_lithium_7',
        type = 'fluid',
        icon = sprite('fu_lithium_7.png'),
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        heat_capacity = '1kJ',
        base_color = { r=0.0, g=0.3, b=0.4 }, 
		flow_color = { r=0.0, g=0.3, b=0.4 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0.290,
        subgroup = 'fu_item_subgroup_f',
        order = 'a-a',
    },
    {
        name = 'fu_lithium_7_heated',
        type = 'fluid',
        icon = sprite('fu_lithium_7_heated.png'),
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        heat_capacity = '1kJ',
        base_color = { r=0.0, g=0.3, b=0.4 }, 
		flow_color = { r=0.0, g=0.3, b=0.4 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0.290,
        subgroup = 'fu_item_subgroup_f',
        order = 'a-a',
    },
    {
        name = 'fu_sulfur',
        type = 'fluid',
        icon = sprite('fu_sulfur.png'),
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        heat_capacity = '1kJ',
        base_color = { r=0.0, g=0.3, b=0.4 }, 
		flow_color = { r=0.0, g=0.3, b=0.4 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0.290,
        subgroup = 'fu_item_subgroup_f',
        order = 'a-a',
    },
    {
        name = 'fu_sulfur_heated',
        type = 'fluid',
        icon = sprite('fu_sulfur_heated.png'),
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        heat_capacity = '1kJ',
        base_color = { r=0.0, g=0.3, b=0.4 }, 
		flow_color = { r=0.0, g=0.3, b=0.4 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0.290,
        subgroup = 'fu_item_subgroup_f',
        order = 'a-a',
    },
    {
        name = 'fu_uranium_238',
        type = 'fluid',
        icon = sprite('fu_uranium_238.png'),
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        heat_capacity = '1kJ',
        base_color = { r=0.0, g=0.3, b=0.4 }, 
		flow_color = { r=0.0, g=0.3, b=0.4 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0.290,
        subgroup = 'fu_item_subgroup_f',
        order = 'a-a',
    },
    {
        name = 'fu_uranium_238_heated',
        type = 'fluid',
        icon = sprite('fu_uranium_238_heated.png'),
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        heat_capacity = '1kJ',
        base_color = { r=0.0, g=0.3, b=0.4 }, 
		flow_color = { r=0.0, g=0.3, b=0.4 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0.290,
        subgroup = 'fu_item_subgroup_f',
        order = 'a-a',
    },
    {
        name = 'fu_uranium_235',
        type = 'fluid',
        icon = sprite('fu_uranium_235.png'),
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        heat_capacity = '1kJ',
        base_color = { r=0.0, g=0.3, b=0.4 }, 
		flow_color = { r=0.0, g=0.3, b=0.4 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0.290,
        subgroup = 'fu_item_subgroup_f',
        order = 'a-a',
    },
    {
        name = 'fu_uranium_235_heated',
        type = 'fluid',
        icon = sprite('fu_uranium_235_heated.png'),
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        heat_capacity = '1kJ',
        base_color = { r=0.0, g=0.3, b=0.4 }, 
		flow_color = { r=0.0, g=0.3, b=0.4 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0.290,
        subgroup = 'fu_item_subgroup_f',
        order = 'a-a',
    },
})