--local functions
local function config(name)
    return settings.startup[name].value
end

local function sprite(name)
    return '__248k__/ressources/fluids/'..name
end

data:extend({
    {
        name = 'el_pressurized_water',
        type = 'fluid',
        icon = sprite('el_pressurized_water.png'),
        icon_size = 64,
        default_temperature = 100,
        max_temperature = 1000,
        heat_capacity = '1kJ',
        base_color = { r=0.0, g=0.3, b=0.4 }, 
		flow_color = { r=0.0, g=0.3, b=0.4 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0,
        subgroup = 'el_item_subgroup_e',
        order = 'a-a',
    },
    {
        name = 'el_kerosene',
        type = 'fluid',
        icon = sprite('el_kerosene.png'),
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        heat_capacity = '10kJ',
        base_color = { r=0.76, g=0.45, b=0.3 }, 
		flow_color = { r=0.76, g=0.45, b=0.3 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0,
        subgroup = 'el_item_subgroup_e',
        order = 'a-b',
    },
    {
        name = 'el_acidic_water',
        type = 'fluid',
        icon = sprite('el_acidic_water.png'),
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        heat_capacity = '1kJ',
        base_color = { r=0.55, g=0.82, b=0.51 }, 
		flow_color = { r=0.55, g=0.82, b=0.51 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0,
        subgroup = 'el_item_subgroup_e',
        order = 'a-c',
    },
    {
        name = 'el_desulfurized_kerosene',
        type = 'fluid',
        icon = sprite('el_desulfurized_kerosene.png'),
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        heat_capacity = '2kJ',
        base_color = { r=0.9, g=0.77, b=0.6 }, 
		flow_color = { r=0.9, g=0.77, b=0.6 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0,
        subgroup = 'el_item_subgroup_e',
        order = 'a-d',
    },
    {
        name = 'el_ki_memory_fluid',
        type = 'fluid',
        icon = sprite('el_ki_memory_fluid.png'),
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        heat_capacity = '1kJ',
        base_color = { r=0.9, g=0.77, b=0.6 }, 
		flow_color = { r=0.9, g=0.77, b=0.6 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0,
        subgroup = 'el_item_subgroup_e',
        order = 'a-e',
    },
    {
        name = 'el_ki_cpu_fluid',
        type = 'fluid',
        icon = sprite('el_ki_cpu_fluid.png'),
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        heat_capacity = '1kJ',
        base_color = { r=0.9, g=0.77, b=0.6 }, 
		flow_color = { r=0.9, g=0.77, b=0.6 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0,
        subgroup = 'el_item_subgroup_e',
        order = 'a-e',
    },
    {
        name = 'fi_ki_circuit_fluid',
        type = 'fluid',
        icon = sprite('fi_ki_circuit_fluid.png'),
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        heat_capacity = '1kJ',
        base_color = { r=0.9, g=0.77, b=0.6 }, 
		flow_color = { r=0.9, g=0.77, b=0.6 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0,
        subgroup = 'el_item_subgroup_e',
        order = 'a-e',
    },
    {
        name = 'fu_ki_circuit_fluid',
        type = 'fluid',
        icon = sprite('fu_ki_circuit_fluid.png'),
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        heat_capacity = '1kJ',
        base_color = { r=0.9, g=0.77, b=0.6 }, 
		flow_color = { r=0.9, g=0.77, b=0.6 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0,
        subgroup = 'el_item_subgroup_e',
        order = 'a-e',
    },
    {
        name = 'fi_crystal_fluid',
        type = 'fluid',
        icon = sprite('fi_crystal_fluid.png'),
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        heat_capacity = '1kJ',
        base_color = { r=0.9, g=0.77, b=0.6 }, 
		flow_color = { r=0.9, g=0.77, b=0.6 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0,
        subgroup = 'fi_item_subgroup_f',
        order = 'a-a',
    },
    {
        name = 'fu_lead_fluid',
        type = 'fluid',
        icon = sprite('fu_lead_fluid.png'),
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1500,
        heat_capacity = '100kJ',
        base_color = { r=0.9, g=0.77, b=0.6 }, 
		flow_color = { r=0.9, g=0.77, b=0.6 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0,
        subgroup = 'fu_item_subgroup_e',
        order = 'a-a',
    },
})